### ISSUE TITLE
Is this method works with other PQ methods? (OPQ, LOPQ)

### ISSUE THREAD

**Issue by insikk** [DwangoMediaVillage/pqkmeans#15]
My main goal is minimizing error of PQk-means clustering that comes from quantization.
I want to use PQk-means clustering over Ak-means (Approximate k-means clustering with kd-tree forest) because of the fantastic speed. At the same time, I want to minimize error discrepancy between PQk-means and Ak-means. 

There are few parameters I know to do that. 
* Increase M and L to make more accurate approximation of corresponding original vector. 

However, from this picture from http://image.ntua.gr/iva/research/lopq/
![image](https://user-images.githubusercontent.com/2110359/34291765-1f6a751c-e741-11e7-8aae-a013f80e901c.png)

I can see PQ has inherent limitation for approximate quantization compare to LOPQ. That is why I came up with idea of using LOPQ on PQk-means clustering. 

I am new to PQ worlds, so I am not sure if PQk-means's assignment and update are still valid for other methods such as OPQ and LOPQ. 

Do you have any idea?

**Comment by matsui528** [comment]
Hi @insikk 

OPQ is a straightforward extension of PQ, where a rotation matrix is applied for each vector in advance. Implementing OPQ is on my TODO list, but PR is welcome :) 

LOPQ is a different technology, and cannot be combined to the current PQk-means.

The SOTA search system consists of (1) coarse quantization and (2) PQ compression for each vector. LOPQ is a strategy to train the coarse-quantizer in the per-cell manner, whereas PQk-means does not include coarse-quantization step (because maintaining such data structure is an additional cost in our setting).

**Comment by insikk** [comment]
Thank you for your kind explanation. Now I understand what is the difference. 

I am really looking forward OPQ implementation. 
Because I don't know much about OPQ, I don't think I can send PR on this feature. 

Meanwhile, I might able to plug and play with external OPQ library. Can you recommend any C++, C++ + Python binding, or Pure Python implementation of OPQ?

**Comment by matsui528** [comment]
OPQ is an encoding step, so it should be pure Python (pq_encoder.py). Actually I have my own C++ implementation of OPQ. I'll port it to Python (maybe next month)

**Comment by ParadoxZW** [comment]
May I get your C++ implementation of OPQ encoding (just for educational purpose)? This is my email: zweigshao@qq.com.  I'll really appreciate it if you could send me a copy.

**Comment by matsui528** [comment]
Oh I had completely forgotten about this issue 😂   Python implemention of OPQ is available here https://github.com/matsui528/nanopq
