### ISSUE TITLE
Can't pip install

### ISSUE THREAD

**Issue by jen0liu** [DwangoMediaVillage/pqkmeans#29]
Error message `FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'`

**Comment by matsui528** [comment]
Hi @jen0liu 
Please install CMake before running pip
https://github.com/DwangoMediaVillage/pqkmeans#installation

**Comment by GreenHand1998** [comment]
![1O15}@C(0E8EBZH@F14YEY](https://github.com/DwangoMediaVillage/pqkmeans/assets/155615558/808ee8f6-f53d-4767-9f0d-552f8dd0aefe)
![VOTR7U{KL1@(DU47JF0NX9S](https://github.com/DwangoMediaVillage/pqkmeans/assets/155615558/0c61df07-9dcc-484e-948b-c6530975a1b9)
Please ask the author, I keep showing that Cmake fails here, but it has been installed, and I also added the Path to the environment configuration variable path. Is it because Cmake is not configured in Pycharm?
