### ISSUE TITLE
Update cluster

### ISSUE THREAD

**Issue by pablocael** [DwangoMediaVillage/pqkmeans#43]
Hi there. First of all, thanks for this incredibly amazing project!! This is such a helpful and well designed code.

This is not an issue but rather a question, so sorry about using this channel for this:

Is there a way of efficiently updating the kmeans cluster when new data arrives? Im guessing the answer is no and I suppose I have to regenerate the kmeans cluster, as it would be the usual path technically, because new data can slowly change all centroids.. Is that correct or there is some clever way of doing this? 

Thanks!

**Comment by matsui528** [comment]
The k-means training can be rerun using new data with a single iteration, as follows.
- Set the current centers as the initial centers
- Slowly update the centers, i.e., instead of replacing the old centers with new ones, update the old centers gradually in the new direction

Then all vectors can be reassigned to the new center. It may be enough to update only the vectors whose centers have been updated significantly.

**Comment by pablocael** [comment]
Thanks!

**Comment by pablocael** [comment]
Hi, another question if you don't mind. 
Can I use the pqencoder to reduce dimensionality of a feature database and then use sklearn.neighbors.NearestNeighbors on the encoded vectors?

Thanks

**Comment by matsui528** [comment]
You need to reconstruct the original vector from a PQ-code. See `X2_reconstructed = encoder.inverse_transform(X2_pqcode)` in the tutorial https://github.com/DwangoMediaVillage/pqkmeans/blob/master/tutorial/1_pqkmeans.ipynb

Then you can run sklearn search on the reconstructed vectors.
